# every action has a name
name: Clean up old versions
# description
description: Remove old deb packages from the nais-ppa

# definition how we want our action
runs:
  using: docker # we are saying this action will run on docker
  image: 'Dockerfile' # we will use our own Dockerfile to build an image and run it.
