# every action has a name
name: Add package to nais-ppa
# description
description: Add a deb package to the nais-ppa

inputs:
  repo_key:
    description: "SSH key with push access to the PPA-repo"
    required: false
  gpg_private_key:
    description: "GPG key for signing the PPA"
    required: true
  gpg_passphrase:
    description: "GPG passphrase for above key"
    required: true


# definition how we want our action
runs:
  using: docker # we are saying this action will run on docker
  image: 'Dockerfile' # we will use our own Dockerfile to build an image and run it.
  env:
    REPO_KEY: "${{ inputs.repo_key }}"
    GPG_PRIVATE_KEY: "${{ inputs.gpg_private_key }}"
    GPG_PASSPHRASE: "${{ inputs.gpg_passphrase }}"
