name: Update PPA

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "*.deb"

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Cleanup old versions
        uses: ./.github/actions/cleanup
      - name: Update PPA
        uses: ./.github/actions/update
        with:
          gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.PPA_GPG_PASSPHRASE }}
      - name: Push changes
        uses: ad-m/github-push-action@master
